name: Recovery Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Enter the image tag for manual recovery (tag., 20230911_123456)'
        required: true
        default: ''

jobs:
  recover:
    runs-on: self-hosted
    steps:
    - name: Restart Docker Compose
      working-directory: /opt/project
      run: |
        WEBSITE_IMAGE_TAG=${{ github.event.inputs.image_tag }} docker compose up -d website
